Add direct policy attachment
terraform-aws-modules/terraform-aws-iam pull request #387
Opened 2023-05-29 13:51 UTC by SlavaNL

## Description
Add ability to assign a list of custom IAM Policies to selected IAM User during creation

## Motivation and Context
Sometimes IAM Users require some elevation of privileges without including other groups. Also some projects should have a single user without a group, for example the `terraform` user with pre-existing policies to deploy resources. Does not make sense to create a group for this purpose, so the ability to add some policies to IAM User is a nice feature.

## Breaking Changes
None

## How Has This Been Tested?
- [x] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [x] I have executed `pre-commit run -a` on my pull request

2023-06-22 17:49 UTC, cameron-mcdougle-arturoai commented
This would be really helpful! Thank you. You have my vote for merging.

2023-06-30 10:23 UTC, joelgaria commented
Please add this functionality

2023-07-17 10:02 UTC, antonbabenko requested changes
Almost great. Minor comments.

2023-07-17 10:02 UTC, antonbabenko commented on modules/iam-user/outputs.tf
> +output "custom_iam_policy_arns" {
```suggestion
output "policy_arns" {
```

The word `custom` is obsolete in this context. Please change the input variable name as well.

2023-07-19 09:42 UTC, antonbabenko requested changes
Let's be consistent and rename `custom_iam_policy_arns` to `policy_arns` everywhere.

2023-07-19 10:09 UTC, SlavaNL commented
@antonbabenko Thanks, I finished it

2023-07-19 10:12 UTC, antonbabenko commented on examples/iam-user/main.tf
> +# IAM user with AmazonSNSReadOnlyAccess policy assigned
```suggestion
# IAM user with IAM policy attached
```

2023-07-19 10:12 UTC, antonbabenko approved these changes

2023-07-19 10:31 UTC, merged

2023-07-19 10:31 UTC, antonbabenko commented
This PR is included in version 5.28.0 :tada:

2023-08-08 05:41 UTC, igor-nikiforov commented
Unfortunately this not working as expected. See https://github.com/terraform-aws-modules/terraform-aws-iam/issues/408