feat: added variable trusted_role_actions to sub modules as a Extra action of STS
terraform-aws-modules/terraform-aws-iam pull request #393
Opened 2023-06-20 07:56 UTC by tcharewicz

## Description
Orginaly I create issue with "Adding variable trusted_role_actions to other sub-modules"
    - iam-assumable-roles
    - iam-assumable-role-with-saml
    - iam-assumable-roles-with-saml

https://github.com/terraform-aws-modules/terraform-aws-iam/issues/392

At the time of PR creation I found that, in sub module iam-assumable-role-with-saml this variable is used, but in different way comparing to sub module iam-assumable-role. 

In module with iam-assumable-role-with-saml is used as a "Extra Actions of STS"
```
variable "trusted_role_actions" {
  description = "Extra Actions of STS"
  type        = list(string)
  default     = [""]
}
``` 

In module with iam-assumable-role is used as a "Actions of STS"
```
variable "trusted_role_actions" {
  description = "Actions of STS"
  type        = list(string)
  default     = ["sts:AssumeRole"]
}
```

That way finally PR is adding this variable as a "Extra Actions of STS" to sub modules:
- iam-assumable-role
- iam-assumable-roles
- iam-assumable-roles-with-saml

## Motivation and Context
It's useful to use two additional action with STS action:

    sts:SetSourceIdentity
    sts:TagSession

But when you want to use them, you need to add them to all roles in AWS Account.

## Breaking Changes
None, all orginal default action are preserved.

## How Has This Been Tested?
- [yes] I have executed `pre-commit run -a` on my pull request

2023-06-20 11:23 UTC, bryantbiggs requested changes

2023-06-21 15:09 UTC, tcharewicz commented on modules/iam-assumable-roles/main.tf
> -    actions = ["sts:AssumeRole"]
It's changed like you said. In this modules this variable is right now a list of STS actions. Please review PR.

2023-06-29 13:58 UTC, bryantbiggs approved these changes

2023-06-29 13:58 UTC, bryantbiggs commented on modules/iam-assumable-roles/main.tf
> -    actions = ["sts:AssumeRole"]
apologies - it looks like we have/had multiple different methods in use across the modules here. reverted back to the concatting you had originally proposed

2023-06-29 14:06 UTC, merged

2023-06-29 14:07 UTC, antonbabenko commented
This PR is included in version 5.23.0 :tada:

2023-06-29 15:16 UTC, tcharewicz commented
@bryantbiggs Thx.