feat(iam-user): Fixed direct policy attachment in iam-user module
terraform-aws-modules/terraform-aws-iam pull request #421
Opened 2023-09-04 06:53 UTC by garylau

## Description
When creating the `iam-user` module, it throws error as `for_each` is expecting a map or a set of string however the module defines the `policy_arns` variable as a `list(string)`.

## Motivation and Context
Fixes https://github.com/terraform-aws-modules/terraform-aws-iam/issues/408

There are two options to fix this issue. Option 1 is to cast the `policy_arns` into a map of string in runtime (like how it is done in https://github.com/terraform-aws-modules/terraform-aws-iam/blob/master/modules/iam-eks-role/main.tf#L78). Or option 2 is to replace `for_each` with `count`. For simplicity reason, I chose option 2.

## Breaking Changes
None

## How Has This Been Tested?
- [ ] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
example remains the same as there is no change to the caller inputs
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [ ] I have executed `pre-commit run -a` on my pull request

2023-09-06 03:19 UTC, garylau commented
@antonbabenko hello, any chance you may take a look? thank you!

2023-09-27 05:30 UTC, igor-nikiforov commented
@antonbabenko @bryantbiggs could you please take a look this PR?

2023-09-27 07:20 UTC, antonbabenko requested changes
Sorry for the delay with the review. Let's stick to `for_each` and make it changed as here - https://github.com/terraform-aws-modules/terraform-aws-iam/blob/master/modules/iam-eks-role/main.tf#L78

2023-10-10 12:12 UTC, diosif-cr commented
@antonbabenko I've created a PR with your proposal, as I've stumbled upon this issue today.

https://github.com/terraform-aws-modules/terraform-aws-iam/pull/428

2023-11-20 00:10 UTC, closed without merging