feat(iam-role-for-service-accounts-eks): Add support for pod identity service
terraform-aws-modules/terraform-aws-iam pull request #442
Opened 2023-12-03 11:06 UTC by pdrastil

Hi, I would like to contribute support for new EKS pod identity service that allows to use EKS IAM roles without OIDC provider section. Please advice if version.tf should be bumped to >= 5.29 as `aws_eks_pod_identity_association` is required for this scenario.

Usage:
```yaml
module "external_dns" {
  role_name                               = "${module.eks.cluster_name}-external-dns"
  attach_external_dns_policy = true
}

resource "aws_eks_pod_identity_association" "external_dns" {
  cluster_name     = module.eks.cluster_name
  namespace         = "kube-system"
  service_account = "external-dns"
  role_arn              = module.irsa.iam_role_arn
}
```

2023-12-03 12:35 UTC, bryantbiggs commented
We can add the service trust, but this module will be the new home for pod identity (it will be move into this org once it's ready) 

https://github.com/clowdhaus/terraform-aws-eks-pod-identity

2023-12-03 13:21 UTC, bryantbiggs requested changes
Lets hold off on this for now - the addons need to support Pod Identity before the roles generated here can be used

2024-01-03 16:54 UTC, danielloader commented
> Lets hold off on this for now - the addons need to support Pod Identity before the roles generated here can be used

Could you explain what you mean by this? I am looking forward to the feature so as to deprecate and remove all my IRSA roles.

2024-01-03 18:12 UTC, pdrastil commented
@danielloader - I think you are right about AWS SDK. At the time this PR was opened most of the commonly used AWS add-ons weren't working properly with pod identity agent (ALB, EFS, EBS, VPC, etc.).

2024-02-06 12:58 UTC, truongnht commented
@pdrastil any idea on the current status of Pod Identity Agent and AWS addons and where do you track this info?

2024-03-17 16:17 UTC, pdrastil commented
@bryantbiggs Hi any update on IAM support as the EKS 20.x module supports identity providers as input.

2024-03-17 18:43 UTC, truongnht commented
@pdrastil, not sure why we have no response from @bryantbiggs. In our team, we have decided to fork the repo to consume internally

2024-03-18 00:27 UTC, bryantbiggs commented
Been a bit busy, we'll get that released this week

2024-03-20 20:17 UTC, closed without merging

2024-03-20 20:17 UTC, bryantbiggs commented
closing now that this is available https://github.com/terraform-aws-modules/terraform-aws-eks-pod-identity

2024-03-20 22:00 UTC, ivan-sukhomlyn commented
@bryantbiggs thanks 🚀 
could you please clarify if the [terraform-aws-eks-pod-identity](https://github.com/terraform-aws-modules/terraform-aws-eks-pod-identity) module will include `aws_eks_pod_identity_association` Terraform resource management for IAM role association with appropriate k8s SA?

2024-03-21 00:09 UTC, bryantbiggs commented
https://github.com/terraform-aws-modules/terraform-aws-eks-pod-identity/pull/4

I still don't know where the best place to put this association is - I suspect it will end up in multiple places based on the different ways folks may want to manage this, and I guess thats ok

2024-03-21 18:03 UTC, ivan-sukhomlyn commented
Thank you! 🚀 
In my opinion, this module is the best place for association management, considering the module name `eks-pod-identity` (not a `terraform-aws-eks-pod-identity-iam`, etc.), which self-speaks about complete management, not only an IAM role. Furthermore, users can choose the most convenient way based on their requirements.

2024-03-21 19:33 UTC, truongnht commented
> @pdrastil, not sure why we have no response from @bryantbiggs. In our team, we have decided to fork the repo to consume internally

so, when we kinda fork this repo, we also make `eks-pod-identity` doing taking care of 
1. Pod identity role with correct `assume-role` policy
2. Attach whatever necessary policy from calling consumer (e.g cert-manager will provide necessary documents to attach to the role). 
3. Also add `aws_eks_pod_identity_association`

We believe this way would make the module generic enough to be consumed by whoever needs the role. We believe the responsibility of adding correct policy should not be within the module.

2024-03-21 19:55 UTC, bryantbiggs commented
> We believe the responsibility of adding correct policy should not be within the module.

Why not? How many different policy variants can one have for external-dns, cluster-autoscaler, etc.? These commonly used applications need IAM permissions, why not make that easy for users. The new Pod Identity module is flexible enough to where you can extend these permissions, or even provide your own permissions (i.e. - not use the pre-canned policies we provide)

2024-03-21 20:52 UTC, truongnht commented
who knows what's gonna change for `external-dns` and `cluster-autoscaler` and others? When such a change happens, where do you expect to update? Imho tt's about where the change should happen and should be updated.

2024-03-21 21:14 UTC, pdrastil commented
@bryantbiggs In my personal opinion I think that Pod Identity association should be optional / decoupled from IAM role. The main use case I see for new pod identity is to consolidate large amount of same IAM roles for core add-ons used by fleet of clusters that live in same AWS account to single IAM role. If you want to do 1:1 mapping between role and cluster it probably doesn't matter if you use IRSA or Pod Identity resource.

2024-03-21 21:26 UTC, danielloader commented
Have to respectfully disagree. If I can use pod identity associations for once and done things like the AWS ALB controller, cert manager etc I don't need to play the chicken and egg situation of trying to hand down namespaces, service accounts with annotations into a cluster at terraform time before helm deploys they charts.

Personally I'll almost exclusively be using pod identity associations in my cluster for cluster admin level services and charts not workloads from developers. 

It's deeply frustrating trying to fully gitops your system with ArgoCD if you play such games with owning your namespaces and service accounts in terraform outside the state inside kubernetes.

2024-03-21 21:36 UTC, pdrastil commented
@danielloader I do full GitOps with Argo CD and faced the same frustration with context injection :). The best solution I've seen so far was presented on last ArgoCon that uses AppSets to bootstrap the cluster and context is injected to cluster secret as annotations that contain SA names, IAM roles, toggles, etc. Check https://github.com/gitops-bridge-dev with samples. Second option you can do is to create custom plugin that loads this metadata from somewhere (K8s resource or external system), however it might be painful to maintain this in longterm.

2024-03-21 21:41 UTC, danielloader commented
Yeah it's totally possible and yeah I'm using that pattern, also on the same topic there's an issue I'm debating about it on the repository in question - https://github.com/gitops-bridge-dev/gitops-bridge/issues/42.

I just fundamentally don't like IRSA much, the tight coupling makes things quite painful, even if it's possible (which it is since I'm running it in prod) I'd be happier without it.

That said this isn't a hill I'd die on, and worst case scenario someone can maintain a small module of well known IAM policies for common kubernetes addons, and plug this all together painlessly.

2024-03-21 22:21 UTC, pdrastil commented
To clarify my statement about associations being optional - it was more related to TF implementation where some users might want to have 1:1 mapping similar to IRSA with`aws_eks_pod_identity_association` built into the TF module and some users might want to create IAM without specific EKS cluster for 1:N mapping and create association later on. I agree that using Pod Identity for GitOps environments makes integrations easier without necessary context passing.