fix: removed provider from list of attribute of oidc_providers
terraform-aws-modules/terraform-aws-iam pull request #452
Opened 2024-01-16 16:34 UTC by AndrewCharlesHay

## Description
The `provider` attribute is never accessed and thus shouldn't be listed. It also changes the type of `oidc_providers` from any to a map of any because it is a map.

## Motivation and Context
It clutters the requirements for the variable and thus should be removed

## Breaking Changes
If someone used to pass something into `oidc_providers` it will now throw an error at an earlier stage of validation

## How Has This Been Tested?
- [ ] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [ ] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [ ] I have executed `pre-commit run -a` on my pull request

2024-01-16 17:32 UTC, AndrewCharlesHay commented
I didn't mean to commit the SID addition to this PR. I can make a new PR if you want.

2024-01-16 19:20 UTC, bryantbiggs requested changes

2024-01-16 19:20 UTC, bryantbiggs commented on modules/iam-role-for-service-accounts-eks/main.tf
> +      sid     = "OIDCRoleAssumption${index(var.oidc_providers, each.value) + 1}"
please revert this change

2024-01-16 19:20 UTC, bryantbiggs commented on modules/iam-role-for-service-accounts-eks/variables.tf
> -  type        = any
this is intentional - please revert this change

2024-01-16 20:26 UTC, bryantbiggs approved these changes
thank you

2024-01-16 20:26 UTC, merged

2024-01-16 21:06 UTC, AndrewCharlesHay commented
@bryantbiggs Thank you for the merge! I understand if you want them in a separate PR. But what is wrong with changing the type to `map(any)` instead of just `any`?

2024-01-16 21:20 UTC, bryantbiggs commented
when you go with a type, other than `any`, you are forcing users into using the same shape on every input. so for example, if you had something like the following that was acceptable for use by the underlying resource, if you used `any` it will work, if you used `map(any)`, it will complain that the objects are of different types (one has `colors` and the other does not):

```hcl
  foo = {
    one = {
      hot = true
      cups = 2
      colors = ["orange", "blue"]
    }
    two = {
      hot = false
      cups = 1
    }
  }
```

So we typically just default to `any` for complex types so that users have the most flexibility and can provide only the values they wish

2024-01-16 23:42 UTC, AndrewCharlesHay commented
Ohh yeah I've run into that before. So we would want to ensure that every object has just `provider_arn` and `namespace_service_accounts` right? I guess the issue would be when the key, in your example `one` and `two` would be different

2024-01-16 23:49 UTC, AndrewCharlesHay commented
Both attributes are referenced in each [iteration](https://github.com/AndrewCharlesHay/terraform-aws-iam/blob/e63dff8de9f6aee7e9ebfbe8c676fa980f5233c0/modules/iam-role-for-service-accounts-eks/main.tf#L52) so we need both and wouldn't want anything else right? I guess it would somewhat unnecessarily make things not backwards compatible.

2024-01-18 01:24 UTC, antonbabenko commented
This PR is included in version 5.33.1 :tada: